#!/bin/bash

set -o errexit

set -o nounset


worker_ready(){
    celery worker -A my_blog inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available :-('
    sleep 1

done
>&2 echo 'Celery workers are available and ready!...:-)'

flower \
    --app=my_blog \
    --broker="${CELERY_BROKER}"
