#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset


find . -name "0001_initial.py" -exec /bin/rm {} \;
python3 manage.py makemigrations
python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000
