#image: docker:20.10
#
#services:
#  - docker:20.10-dind
#
#variables:
#  DOCKER_TLS_CERTDIR: "/certs"
#
#
#stages:
#  - build
#  - test
#  - deploy
#
#before_script:
#  - apk update
#  - apk add py3-pip
#  - apk add docker-compose
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
##  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#
#
#build:
#  stage: build
#  script:
#    - docker-compose -f docker-compose-production.yml build
#    - docker-compose -f docker-compose-production.yml push
#  artifacts:
#    paths:
#      - docker-compose-production.yml
#  only:
#    - main
#
#test:
#  stage: test
#  script:
#    - docker-compose -f docker-compose-production.yml run web_app python manage.py test
#  dependencies:
#    - build
#  only:
#    - test
#
#deploy:
#  stage: deploy
#  environment:
#    name: production
#  script:
#    - docker-compose -f docker-compose-production.yml pull
#    - docker-compose -f docker-compose-production.yml up -d
#  dependencies:
#    - build
#  only:
#    - main
#

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - deploy

test:
  image: python:3.9
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test
  only:
    - main

deploy:
  stage: deploy
  image: docker/compose:latest
  script:
    - docker login -u whisky973 -p PAPApadeo1
    - docker-compose -f docker-compose-production.yml up -d
  environment:
    name: production
  only:
    - main
  when: on_success
